-- MySQL Script generated by MySQL Workbench
-- Sun Jun 27 16:45:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HousePricingAppDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HousePricingAppDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HousePricingAppDb` DEFAULT CHARACTER SET utf8 ;
USE `HousePricingAppDb` ;

-- -----------------------------------------------------
-- Table `HousePricingAppDb`.`Requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HousePricingAppDb`.`Requests` (
  `idRequests` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP GENERATED ALWAYS AS () VIRTUAL,
  `LotArea` INT NOT NULL,
  `YearBuilt` INT NOT NULL,
  `FstFlrSF` INT NOT NULL,
  `SndFlrSF` INT NOT NULL,
  `FullBath` INT NOT NULL,
  `BedroomAbvGr` INT NOT NULL,
  `TotRmsAbvGrd` INT NOT NULL,
  `RequestType` VARCHAR(8) NOT NULL,
  `RequestStatus` INT NOT NULL,
  `Response` LONGTEXT NOT NULL,
  PRIMARY KEY (`idRequests`),
  UNIQUE INDEX `idRequests_UNIQUE` (`idRequests` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
